package self.shaohua.study.mybatis.mapper;

import org.apache.ibatis.annotations.Update;
import self.shaohua.study.mybatis.model.Address;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Mon Mar 04 16:00:56 CST 2019
     */
    int deleteByPrimaryKey(Long addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Mon Mar 04 16:00:56 CST 2019
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Mon Mar 04 16:00:56 CST 2019
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Mon Mar 04 16:00:56 CST 2019
     */
    Address selectByPrimaryKey(Long addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Mon Mar 04 16:00:56 CST 2019
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Mon Mar 04 16:00:56 CST 2019
     */
    int updateByPrimaryKey(Address record);

    @Update("update address set detail='' where address_id = #{addressId} ")
    int removeAddressByPrimaryKey(Long addressId);
}